## Load Data and divide data into 12 slices based on sheets

In [144]:
import numpy as np
import pandas as pd
import plotly.express as px 
import matplotlib.pyplot as plt


xls = pd.ExcelFile("/Users/kyroma/Downloads/Assignment 2 GHGHighlights Data.XLS")
sheetName = {'GHG Energy':'GHG emissions from energy', 
             'GHG Fugi':'GHG Fugitive emissions', 
             'GHG FC':'GHG emissions from fuel combustion', 
             'GHG FC - Coal':'GHG emissions from fuel combustion - Coal', 
             'GHG FC - Oil':'GHG emissions from fuel combustion - Oil', 
             'GHG FC - Gas':'GHG emissions from fuel combustion - Gas', 
             'CO2 MARBUNK':'CO2 emissions from international marine bunkers', 
             'CO2 AVBUNK':'CO2 emissions from international aviation bunkers', 
             'CO2-TES':'CO2 emissions / TES', 
             'CO2-GDP':'CO2 emissions / GDP using exchange rates', 
             'CO2-GDP PPP':'CO2 emissions / GDP using purchasing power parities', 
             'CO2-POP':'CO2 emissions / population'}

dictSheet = {} # extract 12 sheets

for name, value in sheetName.items():
    sheet = pd.read_excel(xls, name)
    dictSheet[name] = sheet
    
dictSheet

{'GHG Energy':          GHG emissions from energy  \
 0                              NaN
 1    Back to the table of contents
 2         million tonnes of CO2 eq
 3                              NaN
 4                            World
 ..                             ...
 193                         Europe
 194                        Oceania
 195                            NaN
 196                            NaN
 197                            NaN

                                             Unnamed: 1   Unnamed: 2  \
 0                                                  NaN          NaN
 1                                                  NaN          NaN
 2                                                 1971         1972
 3                                                  NaN          NaN
 4                                          16266.53196  16975.46905
 ..                                                 ...          ...
 193                                                 ..           ..
 194                                                 ..           ..
 195  The original version of this file, as publishe...          NaN
 196  \nYou are permitted to use the data in this fi...          NaN
 197  This notice, and any copyright or sourcing sta...          NaN

       Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6         Source:  \
 0            NaN          NaN          NaN          NaN  Documentation:
 1            NaN          NaN          NaN          NaN             NaN
 2           1973         1974         1975         1976            1977
 3            NaN          NaN          NaN          NaN             NaN
 4    17915.25169  17867.80151  17898.91539  18897.85765       19493.676
 ..           ...          ...          ...          ...             ...
 193           ..           ..           ..           ..              ..
 194           ..           ..           ..           ..              ..
 195          NaN          NaN          NaN          NaN             NaN
 196          NaN          NaN          NaN          NaN             NaN
 197          NaN          NaN          NaN          NaN             NaN

       Unnamed: 8 IEA (2023), GHG Emissions from Energy  ...  Unnamed: 43  \
 0            NaN                       Accessible here  ...          NaN
 1            NaN                                   NaN  ...          NaN
 2           1978                                  1979  ...         2013
 3            NaN                                   NaN  ...          NaN
 4    19997.16783                           20583.73052  ...  36230.16568
 ..           ...                                   ...  ...          ...
 193           ..                                    ..  ...           ..
 194           ..                                    ..  ...           ..
 195          NaN                                   NaN  ...          NaN
 196          NaN                                   NaN  ...          NaN
 197          NaN                                   NaN  ...          NaN

      Unnamed: 44  Unnamed: 45  Unnamed: 46  Unnamed: 47  Unnamed: 48  \
 0            NaN          NaN          NaN          NaN          NaN
 1            NaN          NaN          NaN          NaN          NaN
 2           2014         2015         2016         2017         2018
 3            NaN          NaN          NaN          NaN          NaN
 4    36325.81173  36166.20226  36206.38192  36746.24163  37629.18139
 ..           ...          ...          ...          ...          ...
 193           ..           ..           ..           ..           ..
 194           ..           ..           ..           ..           ..
 195          NaN          NaN          NaN          NaN          NaN
 196          NaN          NaN          NaN          NaN          NaN
 197          NaN          NaN          NaN          NaN          NaN

     Unnamed: 49  Unnamed: 50 Unnamed: 51 Unnamed: 52
 0           NaN          NaN         NaN         NaN
 1           NaN          NaN         NaN         NaN
 2          2019         2020        2021        2022
 3           NaN          NaN         NaN         NaN
 4    37606.6198  35444.25098  37401.3553          ..
 ..          ...          ...         ...         ...
 193          ..           ..          ..          ..
 194          ..           ..          ..          ..
 195         NaN          NaN         NaN         NaN
 196         NaN          NaN         NaN         NaN
 197         NaN          NaN         NaN         NaN

 [198 rows x 53 columns],
 'GHG Fugi':             GHG Fugitive emissions  \
 0                              NaN
 1    Back to the table of contents
 2            kilo tonnes of CO2 eq
 3                              NaN
 4                            World
 ..                             ...
 193                         Europe
 194                        Oceania
 195                            NaN
 196                            NaN
 197                            NaN

                                             Unnamed: 1   Unnamed: 2  \
 0                                                  NaN          NaN
 1                                                  NaN          NaN
 2                                                 1971         1972
 3                                                  NaN          NaN
 4                                          1967933.465  2006721.938
 ..                                                 ...          ...
 193                                                 ..           ..
 194                                                 ..           ..
 195  The original version of this file, as publishe...          NaN
 196  \nYou are permitted to use the data in this fi...          NaN
 197  This notice, and any copyright or sourcing sta...          NaN

       Unnamed: 3   Unnamed: 4  Unnamed: 5   Unnamed: 6         Source:  \
 0            NaN          NaN         NaN          NaN  Documentation:
 1            NaN          NaN         NaN          NaN             NaN
 2           1973         1974        1975         1976            1977
 3            NaN          NaN         NaN          NaN             NaN
 4    2098386.873  2080256.878  2045539.06  2209330.898     2241982.635
 ..           ...          ...         ...          ...             ...
 193           ..           ..          ..           ..              ..
 194           ..           ..          ..           ..              ..
 195          NaN          NaN         NaN          NaN             NaN
 196          NaN          NaN         NaN          NaN             NaN
 197          NaN          NaN         NaN          NaN             NaN

      Unnamed: 8 IEA (2023), GHG Emissions from Energy  ...  Unnamed: 43  \
 0           NaN                       Accessible here  ...          NaN
 1           NaN                                   NaN  ...          NaN
 2          1978                                  1979  ...         2013
 3           NaN                                   NaN  ...          NaN
 4    2231769.57                           2292206.665  ...  3188092.788
 ..          ...                                   ...  ...          ...
 193          ..                                    ..  ...           ..
 194          ..                                    ..  ...           ..
 195         NaN                                   NaN  ...          NaN
 196         NaN                                   NaN  ...          NaN
 197         NaN                                   NaN  ...          NaN

      Unnamed: 44 Unnamed: 45  Unnamed: 46  Unnamed: 47  Unnamed: 48  \
 0            NaN         NaN          NaN          NaN          NaN
 1            NaN         NaN          NaN          NaN          NaN
 2           2014        2015         2016         2017         2018
 3            NaN         NaN          NaN          NaN          NaN
 4    3214331.718  3192224.55  3181248.695  3187235.335  3279540.428
 ..           ...         ...          ...          ...          ...
 193           ..          ..           ..           ..           ..
 194           ..          ..           ..           ..           ..
 195          NaN         NaN          NaN          NaN          NaN
 196          NaN         NaN          NaN          NaN          NaN
 197          NaN         NaN          NaN          NaN          NaN

      Unnamed: 49  Unnamed: 50 Unnamed: 51  Unnamed: 52
 0            NaN          NaN         NaN          NaN
 1            NaN          NaN         NaN          NaN
 2           2019         2020        2021         2022
 3            NaN          NaN         NaN          NaN
 4    3329830.615  3123712.613   3226016.9  3282306.293
 ..           ...          ...         ...          ...
 193           ..           ..          ..           ..
 194           ..           ..          ..           ..
 195          NaN          NaN         NaN          NaN
 196          NaN          NaN         NaN          NaN
 197          NaN          NaN         NaN          NaN

 [198 rows x 53 columns],
 'GHG FC':     GHG emissions from fuel combustion  \
 0                                  NaN
 1        Back to the table of contents
 2             million tonnes of CO2 eq
 3                                  NaN
 4                                World
 ..                                 ...
 196                            Oceania
 197                                NaN
 198                                NaN
 199                                NaN
 200                                NaN

                                             Unnamed: 1   Unnamed: 2  \
 0                                                  NaN          NaN
 1                                                  NaN          NaN
 2                                                 1971         1972
 3                                                  NaN          NaN
 4                                          14298.59849  14968.74711
 ..                                                 ...          ...
 196                                         159.541608   166.696963
 197                                                NaN          NaN
 198  The original version of this file, as publishe...          NaN
 199  \nYou are permitted to use the data in this fi...          NaN
 200  This notice, and any copyright or sourcing sta...          NaN

       Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6         Source:  \
 0            NaN          NaN          NaN          NaN  Documentation:
 1            NaN          NaN          NaN          NaN             NaN
 2           1973         1974         1975         1976            1977
 3            NaN          NaN          NaN          NaN             NaN
 4    15816.86482  15787.54463  15853.37633  16688.52676     17251.69336
 ..           ...          ...          ...          ...             ...
 196   177.328137   192.952321   198.972916   203.172122      217.834668
 197          NaN          NaN          NaN          NaN             NaN
 198          NaN          NaN          NaN          NaN             NaN
 199          NaN          NaN          NaN          NaN             NaN
 200          NaN          NaN          NaN          NaN             NaN

       Unnamed: 8 IEA (2023), GHG Emissions from Energy  ...  Unnamed: 43  \
 0            NaN                       Accessible here  ...          NaN
 1            NaN                                   NaN  ...          NaN
 2           1978                                  1979  ...         2013
 3            NaN                                   NaN  ...          NaN
 4    17765.39826                           18291.52386  ...  33042.07289
 ..           ...                                   ...  ...          ...
 196    212.48217                            216.963934  ...    419.68132
 197          NaN                                   NaN  ...          NaN
 198          NaN                                   NaN  ...          NaN
 199          NaN                                   NaN  ...          NaN
 200          NaN                                   NaN  ...          NaN

      Unnamed: 44  Unnamed: 45  Unnamed: 46  Unnamed: 47  Unnamed: 48  \
 0            NaN          NaN          NaN          NaN          NaN
 1            NaN          NaN          NaN          NaN          NaN
 2           2014         2015         2016         2017         2018
 3            NaN          NaN          NaN          NaN          NaN
 4    33111.48001  32973.97771  33025.13323  33559.00629  34349.64097
 ..           ...          ...          ...          ...          ...
 196    410.02716   414.580652   421.295484   425.391629     423.2902
 197          NaN          NaN          NaN          NaN          NaN
 198          NaN          NaN          NaN          NaN          NaN
 199          NaN          NaN          NaN          NaN          NaN
 200          NaN          NaN          NaN          NaN          NaN

      Unnamed: 49  Unnamed: 50 Unnamed: 51 Unnamed: 52
 0            NaN          NaN         NaN         NaN
 1            NaN          NaN         NaN         NaN
 2           2019         2020        2021      2022.0
 3            NaN          NaN         NaN         NaN
 4    34276.78919  32320.53837  34175.3384         0.0
 ..           ...          ...         ...         ...
 196   422.190724   404.298482  396.584253         0.0
 197          NaN          NaN         NaN         NaN
 198          NaN          NaN         NaN         NaN
 199          NaN          NaN         NaN         NaN
 200          NaN          NaN         NaN         NaN

 [201 rows x 53 columns],
 'GHG FC - Coal':     GHG emissions from fuel combustion - Coal  \
 0                                         NaN
 1               Back to the table of contents
 2                    million tonnes of CO2 eq
 3                                         NaN
 4                                       World
 ..                                        ...
 196                                   Oceania
 197                                       NaN
 198                                       NaN
 199                                       NaN
 200                                       NaN

                                             Unnamed: 1   Unnamed: 2  \
 0                                                  NaN          NaN
 1                                                  NaN          NaN
 2                                                 1971         1972
 3                                                  NaN          NaN
 4                                          5310.333469  5372.934747
 ..                                                 ...          ...
 196                                          79.690927    83.907768
 197                                                NaN          NaN
 198  The original version of this file, as publishe...          NaN
 199  \nYou are permitted to use the data in this fi...          NaN
 200  This notice, and any copyright or sourcing sta...          NaN

      Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6         Source:  \
 0           NaN          NaN          NaN          NaN  Documentation:
 1           NaN          NaN          NaN          NaN             NaN
 2          1973         1974         1975         1976            1977
 3           NaN          NaN          NaN          NaN             NaN
 4    5573.83282  5603.107085  5717.304556  5946.789037     6133.698862
 ..          ...          ...          ...          ...             ...
 196   86.572744    91.940925    97.631081     97.85595      105.415502
 197         NaN          NaN          NaN          NaN             NaN
 198         NaN          NaN          NaN          NaN             NaN
 199         NaN          NaN          NaN          NaN             NaN
 200         NaN          NaN          NaN          NaN             NaN

       Unnamed: 8 IEA (2023), GHG Emissions from Energy  ...  Unnamed: 43  \
 0            NaN                       Accessible here  ...          NaN
 1            NaN                                   NaN  ...          NaN
 2           1978                                  1979  ...         2013
 3            NaN                                   NaN  ...          NaN
 4    6298.107103                           6574.071877  ...  15207.40339
 ..           ...                                   ...  ...          ...
 196    97.680668                             101.36596  ...   191.160193
 197          NaN                                   NaN  ...          NaN
 198          NaN                                   NaN  ...          NaN
 199          NaN                                   NaN  ...          NaN
 200          NaN                                   NaN  ...          NaN

      Unnamed: 44 Unnamed: 45  Unnamed: 46 Unnamed: 47  Unnamed: 48  \
 0            NaN         NaN          NaN         NaN          NaN
 1            NaN         NaN          NaN         NaN          NaN
 2           2014        2015         2016        2017         2018
 3            NaN         NaN          NaN         NaN          NaN
 4    15224.25646  14729.7372  14504.68604   14736.877  15121.07218
 ..           ...         ...          ...         ...          ...
 196   181.503284   187.51323   192.785105  190.113769   182.847939
 197          NaN         NaN          NaN         NaN          NaN
 198          NaN         NaN          NaN         NaN          NaN
 199          NaN         NaN          NaN         NaN          NaN
 200          NaN         NaN          NaN         NaN          NaN

      Unnamed: 49  Unnamed: 50  Unnamed: 51 Unnamed: 52
 0            NaN          NaN          NaN         NaN
 1            NaN          NaN          NaN         NaN
 2           2019         2020         2021        2022
 3            NaN          NaN          NaN         NaN
 4    14885.59739  14308.24909  15186.17597           0
 ..           ...          ...          ...         ...
 196   179.069053   168.796861   165.361839           0
 197          NaN          NaN          NaN         NaN
 198          NaN          NaN          NaN         NaN
 199          NaN          NaN          NaN         NaN
 200          NaN          NaN          NaN         NaN

 [201 rows x 53 columns],
 'GHG FC - Oil':     GHG emissions from fuel combustion - Oil  \
 0                                        NaN
 1              Back to the table of contents
 2                   million tonnes of CO2 eq
 3                                        NaN
 4                                      World
 ..                                       ...
 196                                  Oceania
 197                                      NaN
 198                                      NaN
 199                                      NaN
 200                                      NaN

                                             Unnamed: 1   Unnamed: 2  \
 0                                                  NaN          NaN
 1                                                  NaN          NaN
 2                                                 1971         1972
 3                                                  NaN          NaN
 4                                          6764.530398  7258.503114
 ..                                                 ...          ...
 196                                          74.745206    75.598432
 197                                                NaN          NaN
 198  The original version of this file, as publishe...          NaN
 199  \nYou are permitted to use the data in this fi...          NaN
 200  This notice, and any copyright or sourcing sta...          NaN

       Unnamed: 3 Unnamed: 4   Unnamed: 5   Unnamed: 6         Source:  \

## Select Canada as country, then sort Canada data of every sheet from Year_2: maximum to Year_1: minimum

In [143]:
regionData = {}

for name, value in sheetName.items():
    rows = dictSheet[name].loc[(dictSheet[name][value] == 'Region/Country/Economy') | (dictSheet[name][value] == 'Canada')]
    del rows[value]
    rowsSorted = rows.sort_values(by = rows.index[1], ascending=False, axis = 1) 
    rowsRenamed = rowsSorted.rename(index={rowsSorted.index[0]: "Year", rowsSorted.index[1]: "Data"})
    rowsRenamed = rowsRenamed.T
    rowsRenamed = rowsRenamed.reset_index(drop=True)
    rowsRenamed['Sheet'] = name
    regionData[name] = rowsRenamed

regionData

{'GHG Energy':     Year        Data       Sheet
 0   2018  629.359238  GHG Energy
 1   2019   621.79049  GHG Energy
 2   2017   615.40825  GHG Energy
 3   2007   606.57362  GHG Energy
 4   2014  605.859177  GHG Energy
 5   2015  602.797586  GHG Energy
 6   2016  601.773091  GHG Energy
 7   2013  596.569597  GHG Energy
 8   2011  589.160694  GHG Energy
 9   2008  586.502533  GHG Energy
 10  2012  584.930184  GHG Energy
 11  2003  583.935868  GHG Energy
 12  2022  582.106631  GHG Energy
 13  2005  581.830508  GHG Energy
 14  2006  575.431989  GHG Energy
 15  2010  575.168236  GHG Energy
 16  2021  573.595728  GHG Energy
 17  2004  569.667647  GHG Energy
 18  2020  563.376166  GHG Energy
 19  2002  562.764885  GHG Energy
 20  2009  557.678771  GHG Energy
 21  2000  551.560373  GHG Energy
 22  2001  544.654728  GHG Energy
 23  1999  531.091476  GHG Energy
 24  1998  521.855624  GHG Energy
 25  1997  512.565281  GHG Energy
 26  1996  496.781321  GHG Energy
 27  1995  481.637794  GHG Energy
 28  1989  478.977252  GHG Energy
 29  1994  469.232781  GHG Energy
 30  1988  463.898554  GHG Energy
 31  1992  456.768214  GHG Energy
 32  1993  453.824791  GHG Energy
 33  1980  452.422689  GHG Energy
 34  1979  446.919451  GHG Energy
 35  1990  446.392899  GHG Energy
 36  1991  442.172825  GHG Energy
 37  1987   431.77854  GHG Energy
 38  1981  431.661037  GHG Energy
 39  1978  430.049127  GHG Energy
 40  1985  428.243755  GHG Energy
 41  1977  428.088238  GHG Energy
 42  1984  426.656595  GHG Energy
 43  1986  419.705394  GHG Energy
 44  1976  415.287662  GHG Energy
 45  1982  414.552507  GHG Energy
 46  1974  413.414006  GHG Energy
 47  1983  407.761511  GHG Energy
 48  1973  404.992836  GHG Energy
 49  1975  404.226583  GHG Energy
 50  1972  385.855912  GHG Energy
 51  1971  366.611813  GHG Energy,
 'GHG Fugi':     Year         Data     Sheet
 0   2022  63124.66978  GHG Fugi
 1   2018  62309.84245  GHG Fugi
 2   2019  62087.31403  GHG Fugi
 3   2021  60785.12258  GHG Fugi
 4   2017  59341.95695  GHG Fugi
 5   2020  58447.70738  GHG Fugi
 6   2016  55463.55833  GHG Fugi
 7   2015   54369.8559  GHG Fugi
 8   2014  54292.91985  GHG Fugi
 9   2013  50141.69813  GHG Fugi
 10  2011   48606.4439  GHG Fugi
 11  2012  47159.42263  GHG Fugi
 12  2007  46780.68235  GHG Fugi
 13  2010  46705.37033  GHG Fugi
 14  2006  45648.75608  GHG Fugi
 15  2008  45228.41055  GHG Fugi
 16  2009  43603.26113  GHG Fugi
 17  2005  42733.74093  GHG Fugi
 18  2004   42648.5314  GHG Fugi
 19  2003   42269.7507  GHG Fugi
 20  2001   41404.3788  GHG Fugi
 21  2002  41009.86833  GHG Fugi
 22  2000  40817.07423  GHG Fugi
 23  1998  40004.22575  GHG Fugi
 24  1999   39571.3387  GHG Fugi
 25  1997  37795.77973  GHG Fugi
 26  1996  36786.58535  GHG Fugi
 27  1995  35874.78375  GHG Fugi
 28  1992   33314.6195  GHG Fugi
 29  1993   33296.0318  GHG Fugi
 30  1994   33156.8846  GHG Fugi
 31  1991  31668.79603  GHG Fugi
 32  1988  31042.23728  GHG Fugi
 33  1989   30469.6138  GHG Fugi
 34  1990  30185.49935  GHG Fugi
 35  1987  29265.85673  GHG Fugi
 36  1985  28500.13135  GHG Fugi
 37  1986  28108.35178  GHG Fugi
 38  1984   26435.2263  GHG Fugi
 39  1980   23767.7296  GHG Fugi
 40  1973  23534.96033  GHG Fugi
 41  1979   23311.4651  GHG Fugi
 42  1982  23081.01463  GHG Fugi
 43  1983  22985.66952  GHG Fugi
 44  1981  22683.66845  GHG Fugi
 45  1972  22350.65423  GHG Fugi
 46  1974   22111.9708  GHG Fugi
 47  1975  21313.45995  GHG Fugi
 48  1971  20994.32288  GHG Fugi
 49  1978  20816.41453  GHG Fugi
 50  1977  20535.95307  GHG Fugi
 51  1976  20196.68745  GHG Fugi,
 'GHG FC':       Year        Data   Sheet
 0     2018  567.049396  GHG FC
 1     2007  559.792938  GHG FC
 2     2019  559.703176  GHG FC
 3     2017  556.066293  GHG FC
 4     2014  551.566258  GHG FC
 5     2015   548.42773  GHG FC
 6     2013  546.427899  GHG FC
 7     2016  546.309533  GHG FC
 8     2003  541.666117  GHG FC
 9     2008  541.274122  GHG FC
 10    2011   540.55425  GHG FC
 11    2005  539.096767  GHG FC
 12    2012  537.770762  GHG FC
 13    2006  529.783233  GHG FC
 14    2010  528.462866  GHG FC
 15    2004  527.019115  GHG FC
 16    2002  521.755016  GHG FC
 17  2022.0  518.981961  GHG FC
 18    2009   514.07551  GHG FC
 19    2021  512.810605  GHG FC
 20    2000  510.743299  GHG FC
 21    2020  504.928459  GHG FC
 22    2001  503.250349  GHG FC
 23    1999  491.520137  GHG FC
 24    1998  481.851398  GHG FC
 25    1997  474.769501  GHG FC
 26    1996  459.994735  GHG FC
 27    1989  448.507638  GHG FC
 28    1995   445.76301  GHG FC
 29    1994  436.075896  GHG FC
 30    1988  432.856317  GHG FC
 31    1980   428.65496  GHG FC
 32    1979  423.607985  GHG FC
 33    1992  423.453595  GHG FC
 34    1993  420.528759  GHG FC
 35    1990    416.2074  GHG FC
 36    1991  410.504029  GHG FC
 37    1978  409.232712  GHG FC
 38    1981  408.977369  GHG FC
 39    1977  407.552285  GHG FC
 40    1987  402.512683  GHG FC
 41    1984  400.221369  GHG FC
 42    1985  399.743624  GHG FC
 43    1976  395.090974  GHG FC
 44    1986  391.597042  GHG FC
 45    1982  391.471493  GHG FC
 46    1974  391.302035  GHG FC
 47    1983  384.775841  GHG FC
 48    1975  382.913123  GHG FC
 49    1973  381.457876  GHG FC
 50    1972  363.505258  GHG FC
 51    1971   345.61749  GHG FC,
 'GHG FC - Coal':     Year        Data          Sheet
 0   2000  126.595248  GHG FC - Coal
 1   2001  123.970096  GHG FC - Coal
 2   2002  120.768622  GHG FC - Coal
 3   2003  119.920032  GHG FC - Coal
 4   2007  118.424124  GHG FC - Coal
 5   1999  117.094176  GHG FC - Coal
 6   1998  116.484676  GHG FC - Coal
 7   2004  113.623066  GHG FC - Coal
 8   2005  111.947806  GHG FC - Coal
 9   2006  110.120269  GHG FC - Coal
 10  1997  109.545934  GHG FC - Coal
 11  1989  108.794148  GHG FC - Coal
 12  2008  108.649085  GHG FC - Coal
 13  1988  108.425156  GHG FC - Coal
 14  1984  104.985474  GHG FC - Coal
 15  1992    104.7233  GHG FC - Coal
 16  1996  102.991813  GHG FC - Coal
 17  1991  101.608015  GHG FC - Coal
 18  1985  101.330963  GHG FC - Coal
 19  1995  101.110276  GHG FC - Coal
 20  1987  100.264337  GHG FC - Coal
 21  1994   99.341075  GHG FC - Coal
 22  1990   96.573046  GHG FC - Coal
 23  1993   96.060909  GHG FC - Coal
 24  1983   95.511771  GHG FC - Coal
 25  1986   93.330415  GHG FC - Coal
 26  2010   93.275428  GHG FC - Coal
 27  2009   90.481858  GHG FC - Coal
 28  2011   87.998183  GHG FC - Coal
 29  1982   87.737565  GHG FC - Coal
 30  1980    82.51821  GHG FC - Coal
 31  1981   82.099154  GHG FC - Coal
 32  2012   80.510759  GHG FC - Coal
 33  2013   76.824736  GHG FC - Coal
 34  1979   76.029567  GHG FC - Coal
 35  2014    75.02272  GHG FC - Coal
 36  1978   70.719259  GHG FC - Coal
 37  2017     70.1089  GHG FC - Coal
 38  1977   69.767341  GHG FC - Coal
 39  2016   69.756631  GHG FC - Coal
 40  2015   69.661659  GHG FC - Coal
 41  1976   65.218054  GHG FC - Coal
 42  1971   64.355988  GHG FC - Coal
 43  1973   60.376262  GHG FC - Coal
 44  1972    59.74345  GHG FC - Coal
 45  1975   59.370223  GHG FC - Coal
 46  1974   59.091478  GHG FC - Coal
 47  2018   57.163865  GHG FC - Coal
 48  2019   54.895807  GHG FC - Coal
 49  2020   44.996297  GHG FC - Coal
 50  2021   42.286125  GHG FC - Coal
 51  2022   29.971597  GHG FC - Coal,
 'GHG FC - Oil':       Year        Data         Sheet
 0     2018  271.288835  GHG FC - Oil
 1     2019   266.75543  GHG FC - Oil
 2     2017  265.471235  GHG FC - Oil
 3     2013   263.30067  GHG FC - Oil
 4     2015  263.054201  GHG FC - Oil
 5     2007  262.784771  GHG FC - Oil
 6     2012  262.294163  GHG FC - Oil
 7     2010   260.90057  GHG FC - Oil
 8     2011  260.591449  GHG FC - Oil
 9     2016  259.758724  GHG FC - Oil
 10    2014    259.0469  GHG FC - Oil
 11    2005  257.434439  GHG FC - Oil
 12    2008  255.607841  GHG FC - Oil
 13    2006  252.176274  GHG FC - Oil
 14    2009  251.815891  GHG FC - Oil
 15    1979  251.137724  GHG FC - Oil
 16    1980  248.264817  GHG FC - Oil
 17    2003  246.950198  GHG FC - Oil
 18    1978  245.995691  GHG FC - Oil
 19    1974  244.830499  GHG FC - Oil
 20    2004  244.029534  GHG FC - Oil
 21  2022.0  243.998424  GHG FC - Oil
 22    1977  241.716874  GHG FC - Oil
 23    1976  238.908788  GHG FC - Oil
 24    1973  236.752618  GHG FC - Oil
 25    1975  234.554857  GHG FC - Oil
 26    2002  234.167008  GHG FC - Oil
 27    2021  234.004386  GHG FC - Oil
 28    2020  231.865532  GHG FC - Oil
 29    1981  231.401745  GHG FC - Oil
 30    1972  224.406614  GHG FC - Oil
 31    2001  220.687783  GHG FC - Oil
 32    2000  218.978936  GHG FC - Oil
 33    1999  217.897594  GHG FC - Oil
 34    1998  215.967108  GHG FC - Oil
 35    1989  215.686308  GHG FC - Oil
 36    1971  211.748862  GHG FC - Oil
 37    1997  211.139506  GHG FC - Oil
 38    1982  206.768555  GHG FC - Oil
 39    1988   205.23588  GHG FC - Oil
 40    1996  203.246987  GHG FC - Oil
 41    1995  198.063268  GHG FC - Oil
 42    1990  197.801077  GHG FC - Oil
 43    1994  195.582966  GHG FC - Oil
 44    1983  194.169865  GHG FC - Oil
 45    1987  194.156195  GHG FC - Oil
 46    1984  193.056462  GHG FC - Oil
 47    1992  190.817761  GHG FC - Oil
 48    1993  190.771844  GHG FC - Oil
 49    1986  189.159927  GHG FC - Oil
 50    1985  188.364143  GHG FC - Oil
 51    1991   187.26798  GHG FC - Oil,
 'GHG FC - Gas':       Year        Data         Sheet
 0   2022.0  241.774813  GHG FC - Gas
 1     2018  235.324054  GHG FC - Gas
 2     2019  234.871876  GHG FC - Gas
 3     2021  233.359605  GHG FC - Gas
 4     2020  224.988123  GHG FC - Gas
 5     2017   217.21886  GHG FC - Gas
 6     2014  214.355097  GHG FC - Gas
 7     2016  213.646978  GHG FC - Gas
 8     2015  212.593916  GHG FC - Gas
 9     2013  203.237593  GHG FC - Gas
 10    2012  192.101225  GHG FC - Gas
 11    2011  189.179452  GHG FC - Gas
 12    2007  176.049723  GHG FC - Gas
 13    2008  174.449663  GHG FC - Gas
 14    2003  172.424728  GHG FC - Gas
 15    2010  171.719356  GHG FC - Gas
 16    2009  169.168371  GHG FC - Gas
 17    2005  167.358126  GHG FC - Gas
 18    2004  166.789491  GHG FC - Gas
 19    2006  165.154106  GHG FC - Gas
 20    2002  164.386704  GHG FC - Gas
 21    2000  162.833163  GHG FC - Gas
 22    2001  156.447212  GHG FC - Gas
 23    1999  153.661947  GHG FC - Gas
 24    1997  151.510541  GHG FC - Gas
 25    1996  150.844357  GHG FC - Gas
 26    1998  146.545576  GHG FC - Gas
 27    1995  143.624588  GHG FC - Gas
 28    1994   138.10653  GHG FC - Gas
 29    1993  131.055072  GHG FC - Gas
 30    1992  125.455725  GHG FC - Gas
 31    1989  122.811123  GHG FC - Gas
 32    1990  119.312997  GHG FC - Gas
 33    1991  119.207628  GHG FC - Gas
 34    1988  117.922336  GHG FC - Gas
 35    1985  108.813231  GHG FC - Gas
 36    1986  107.790919  GHG FC - Gas
 37    1987  106.839805  GHG FC - Gas
 38    1984  100.991135  GHG FC - Gas
 39    1980   96.710047  GHG FC - Gas
 40    1982   95.839347  GHG FC - Gas
 41    1979   95.322487  GHG FC - Gas
 42    1977   95.007936  GHG FC - Gas
 43    1981   94.343958  GHG FC - Gas
 44    1983   93.907598  GHG FC - Gas
 45    1978     91.4147  GHG FC - Gas
 46    1976   89.909595  GHG FC - Gas
 47    1975   87.942103  GHG FC - Gas
 48    1974   86.211627  GHG FC - Gas
 49    1973   83.153525  GHG FC - Gas
 50    1972   78.196619  GHG FC - Gas
 51    1971   68.352657  GHG FC - Gas,
 'CO2 MARBUNK':       Year      Data        Sheet
 0     1978  5.612863  CO2 MARBUNK
 1     1979  5.000934  CO2 MARBUNK
 2     1980  4.758193  CO2 MARBUNK
 3     1998  3.695236  CO2 MARBUNK
 4     1973  3.688697  CO2 MARBUNK
 5     2001  3.632464  CO2 MARBUNK
 6     1972  3.396037  CO2 MARBUNK
 7     2000  3.371733  CO2 MARBUNK
 8     1999  3.321723  CO2 MARBUNK
 9     1974  3.275051  CO2 MARBUNK
 10    1995  3.200963  CO2 MARBUNK
 11    1971  3.099452  CO2 MARBUNK
 12    1994  3.078937  CO2 MARBUNK
 13    1981  3.073934  CO2 MARBUNK
 14    1992  3.072985  CO2 MARBUNK
 15    1991   2.99281  CO2 MARBUNK
 16    1996  2.979822  CO2 MARBUNK
 17    1997  2.938198  CO2 MARBUNK
 18    1990  2.897483  CO2 MARBUNK
 19    2005  2.860405  CO2 MARBUNK
 20    1977  2.834525  CO2 MARBUNK
 21    2007  2.781082  CO2 MARBUNK
 22    1976  2.765937  CO2 MARBUNK
 23    2002  2.754891  CO2 MARBUNK
 24    1993   2.73947  CO2 MARBUNK
 25    2008  2.706361  CO2 MARBUNK
 26    1975  2.607161  CO2 MARBUNK
 27    1982  2.463271  CO2 MARBUNK
 28    2006   2.28185  CO2 MARBUNK
 29    2010  2.201895  CO2 MARBUNK
 30    2009  2.111165  CO2 MARBUNK
 31    1989   2.06464  CO2 MARBUNK
 32    2004  1.933093  CO2 MARBUNK
 33    1983  1.900267  CO2 MARBUNK
 34    1988  1.786182  CO2 MARBUNK
 35    1987  1.720073  CO2 MARBUNK
 36    1984   1.67304  CO2 MARBUNK
 37    2011   1.61928  CO2 MARBUNK
 38    2003  1.587629  CO2 MARBUNK
 39    2018  1.444456  CO2 MARBUNK
 40    2013  1.404678  CO2 MARBUNK
 41    2012  1.326394  CO2 MARBUNK
 42    2017   1.20185  CO2 MARBUNK
 43    1985  1.189088  CO2 MARBUNK
 44    2014  1.174383  CO2 MARBUNK
 45    1986  1.145347  CO2 MARBUNK
 46    2016  1.040098  CO2 MARBUNK
 47    2020   0.91365  CO2 MARBUNK
 48    2019  0.870757  CO2 MARBUNK
 49    2021  0.695657  CO2 MARBUNK
 50    2015  0.691206  CO2 MARBUNK
 51  2022.0       0.0  CO2 MARBUNK,
 'CO2 AVBUNK':       Year       Data       Sheet
 0     2019  15.038579  CO2 AVBUNK
 1     2018  14.883352  CO2 AVBUNK
 2     2017  13.038989  CO2 AVBUNK
 3     2016  11.916169  CO2 AVBUNK
 4     2015  11.324299  CO2 AVBUNK
 5     2013  11.030012  CO2 AVBUNK
 6     2014  10.938923  CO2 AVBUNK
 7     2012  10.569941  CO2 AVBUNK
 8     2007  10.033839  CO2 AVBUNK
 9     2005  10.010608  CO2 AVBUNK
 10    2006   9.874846  CO2 AVBUNK
 11    2011    9.35835  CO2 AVBUNK
 12    2008   9.327643  CO2 AVBUNK
 13    2004   9.060525  CO2 AVBUNK
 14    2010   9.041935  CO2 AVBUNK
 15    2009   8.530631  CO2 AVBUNK
 16    2021   6.537669  CO2 AVBUNK
 17    2020   6.525713  CO2 AVBUNK
 18    2001   3.255867  CO2 AVBUNK
 19    1999   3.121933  CO2 AVBUNK
 20    2000   3.115555  CO2 AVBUNK
 21    1996   3.077289  CO2 AVBUNK
 22    1997   2.997566  CO2 AVBUNK
 23    1998   2.962488  CO2 AVBUNK
 24    2002   2.803043  CO2 AVBUNK
 25    1990   2.732887  CO2 AVBUNK
 26    1989   2.704187  CO2 AVBUNK
 27    1992   2.691432  CO2 AVBUNK
 28    1995    2.60852  CO2 AVBUNK
 29    1991   2.487342  CO2 AVBUNK
 30    1993   2.477775  CO2 AVBUNK
 31    1982    2.46502  CO2 AVBUNK
 32    1994    2.46502  CO2 AVBUNK
 33    1988   2.267308  CO2 AVBUNK
 34    2003   2.158885  CO2 AVBUNK
 35    1977   2.072785  CO2 AVBUNK
 36    1976   2.012196  CO2 AVBUNK
 37    1975   1.948418  CO2 AVBUNK
 38    1978   1.846373  CO2 AVBUNK
 39    1974   1.686928  CO2 AVBUNK
 40    1987   1.632664  CO2 AVBUNK
 41    1979    1.59445  CO2 AVBUNK
 42    1973   1.530672  CO2 AVBUNK
 43    1984   1.517599  CO2 AVBUNK
 44    1986   1.393496  CO2 AVBUNK
 45    1980    1.36166  CO2 AVBUNK
 46    1972   1.339338  CO2 AVBUNK
 47    1971   1.265993  CO2 AVBUNK
 48    1985   1.227673  CO2 AVBUNK
 49    1981   1.125682  CO2 AVBUNK
 50    1983   1.096982  CO2 AVBUNK
 51  2022.0        0.0  CO2 AVBUNK,
 'CO2-TES':     Year    Data    Sheet
 0   1971  57.486  CO2-TES
 1   1974  56.913  CO2-TES
 2   1973  56.304  CO2-TES
 3   1972  56.054  CO2-TES
 4   1977  54.399  CO2-TES
 5   1976  54.351  CO2-TES
 6   1975  54.274  CO2-TES
 7   1978  53.135  CO2-TES
 8   1980  52.539  CO2-TES
 9   1979  52.381  CO2-TES
 10  1981  51.302  CO2-TES
 11  1982  51.123  CO2-TES
 12  1983  50.431  CO2-TES
 13  1984  49.917  CO2-TES
 14  2002  49.378  CO2-TES
 15  1985  48.742  CO2-TES
 16  1989  48.624  CO2-TES
 17  2003  48.612  CO2-TES
 18  2011  48.358  CO2-TES
 19  2010  48.334  CO2-TES
 20  1988  48.233  CO2-TES
 21  2007  48.147  CO2-TES
 22  2012  47.826  CO2-TES
 23  2008   47.71  CO2-TES
 24  2001  47.691  CO2-TES
 25  2000  47.686  CO2-TES
 26  2013  47.636  CO2-TES
 27  1998  47.198  CO2-TES
 28  2009   47.04  CO2-TES
 29  2005  47.024  CO2-TES
 30  1986   46.93  CO2-TES
 31  2015   46.93  CO2-TES
 32  2014  46.855  CO2-TES
 33  1999  46.853  CO2-TES
 34  1987  46.698  CO2-TES
 35  2004  46.454  CO2-TES
 36  1997  46.285  CO2-TES
 37  1990  46.214  CO2-TES
 38  1992  46.062  CO2-TES
 39  1991  45.695  CO2-TES
 40  2006  45.488  CO2-TES
 41  1996   45.28  CO2-TES
 42  2016   44.86  CO2-TES
 43  1995  44.738  CO2-TES
 44  1994  44.341  CO2-TES
 45  1993  44.271  CO2-TES
 46  2018  44.121  CO2-TES
 47  2017  43.842  CO2-TES
 48  2019  43.232  CO2-TES
 49  2020  41.861  CO2-TES
 50  2021  41.592  CO2-TES
 51  2022  41.428  CO2-TES,
 'CO2-GDP':     Year   Data    Sheet
 0   1971  0.719  CO2-GDP
 1   1972  0.717  CO2-GDP
 2   1973  0.703  CO2-GDP
 3   1974  0.695  CO2-GDP
 4   1975  0.669  CO2-GDP
 5   1976  0.655  CO2-GDP
 6   1977  0.654  CO2-GDP
 7   1978  0.632  CO2-GDP
 8   1979  0.631  CO2-GDP
 9   1980  0.624  CO2-GDP
 10  1981  0.575  CO2-GDP
 11  1982  0.568  CO2-GDP
 12  1983  0.545  CO2-GDP
 13  1984  0.535  CO2-GDP
 14  1985   0.51  CO2-GDP
 15  1989  0.504  CO2-GDP
 16  1988  0.498  CO2-GDP
 17  1986  0.489  CO2-GDP
 18  1987  0.483  CO2-GDP
 19  1992   0.48  CO2-GDP
 20  1991  0.469  CO2-GDP
 21  1996  0.466  CO2-GDP
 22  1990  0.466  CO2-GDP
 23  1993  0.464  CO2-GDP
 24  1997  0.461  CO2-GDP
 25  1994  0.461  CO2-GDP
 26  1995  0.459  CO2-GDP
 27  1998  0.451  CO2-GDP
 28  1999  0.437  CO2-GDP
 29  2000  0.433  CO2-GDP
 30  2003   0.43  CO2-GDP
 31  2002  0.422  CO2-GDP
 32  2001  0.419  CO2-GDP
 33  2004  0.406  CO2-GDP
 34  2005  0.402  CO2-GDP
 35  2007  0.398  CO2-GDP
 36  2006  0.385  CO2-GDP
 37  2008  0.381  CO2-GDP
 38  2009  0.373  CO2-GDP
 39  2010  0.372  CO2-GDP
 40  2011  0.369  CO2-GDP
 41  2012  0.361  CO2-GDP
 42  2013  0.358  CO2-GDP
 43  2014  0.351  CO2-GDP
 44  2015  0.347  CO2-GDP
 45  2016  0.342  CO2-GDP
 46  2017  0.338  CO2-GDP
 47  2018  0.336  CO2-GDP
 48  2019  0.325  CO2-GDP
 49  2020  0.309  CO2-GDP
 50  2021  0.299  CO2-GDP
 51  2022  0.292  CO2-GDP,
 'CO2-GDP PPP':     Year   Data        Sheet
 0   1971  0.702  CO2-GDP PPP
 1   1972    0.7  CO2-GDP PPP
 2   1973  0.686  CO2-GDP PPP
 3   1974  0.679  CO2-GDP PPP
 4   1975  0.653  CO2-GDP PPP
 5   1976   0.64  CO2-GDP PPP
 6   1977  0.638  CO2-GDP PPP
 7   1978  0.617  CO2-GDP PPP
 8   1979  0.616  CO2-GDP PPP
 9   1980  0.609  CO2-GDP PPP
 10  1981  0.561  CO2-GDP PPP
 11  1982  0.555  CO2-GDP PPP
 12  1983  0.532  CO2-GDP PPP
 13  1984  0.522  CO2-GDP PPP
 14  1985  0.498  CO2-GDP PPP
 15  1989  0.492  CO2-GDP PPP
 16  1988  0.486  CO2-GDP PPP
 17  1986  0.477  CO2-GDP PPP
 18  1987  0.472  CO2-GDP PPP
 19  1992  0.469  CO2-GDP PPP
 20  1991  0.458  CO2-GDP PPP
 21  1996  0.455  CO2-GDP PPP
 22  1990  0.455  CO2-GDP PPP
 23  1993  0.453  CO2-GDP PPP
 24  1997  0.451  CO2-GDP PPP
 25  1994   0.45  CO2-GDP PPP
 26  1995  0.448  CO2-GDP PPP
 27  1998   0.44  CO2-GDP PPP
 28  1999  0.427  CO2-GDP PPP
 29  2000  0.422  CO2-GDP PPP
 30  2003   0.42  CO2-GDP PPP
 31  2002  0.412  CO2-GDP PPP
 32  2001  0.409  CO2-GDP PPP
 33  2004  0.396  CO2-GDP PPP
 34  2005  0.393  CO2-GDP PPP
 35  2007  0.389  CO2-GDP PPP
 36  2006  0.376  CO2-GDP PPP
 37  2008  0.372  CO2-GDP PPP
 38  2009  0.364  CO2-GDP PPP
 39  2010  0.363  CO2-GDP PPP
 40  2011   0.36  CO2-GDP PPP
 41  2012  0.352  CO2-GDP PPP
 42  2013   0.35  CO2-GDP PPP
 43  2014  0.343  CO2-GDP PPP
 44  2015  0.339  CO2-GDP PPP
 45  2016  0.334  CO2-GDP PPP
 46  2017   0.33  CO2-GDP PPP
 47  2018  0.328  CO2-GDP PPP
 48  2019  0.317  CO2-GDP PPP
 49  2020  0.302  CO2-GDP PPP
 50  2021  0.292  CO2-GDP PPP
 51  2022  0.286  CO2-GDP PPP,
 'CO2-POP':     Year    Data    Sheet
 0   1979  17.243  CO2-POP
 1   1980  17.224  CO2-POP
 2   1977  16.926  CO2-POP
 3   1974  16.895  CO2-POP
 4   2003  16.889  CO2-POP
 5   1978  16.823  CO2-POP
 6   2007  16.783  CO2-POP
 7   1973  16.702  CO2-POP
 8   1976  16.598  CO2-POP
 9   2005  16.489  CO2-POP
 10  2000  16.413  CO2-POP
 11  2002  16.411  CO2-POP
 12  1975  16.295  CO2-POP
 13  2004  16.269  CO2-POP
 14  1981  16.228  CO2-POP
 15  1989  16.213  CO2-POP

## Connect all dataframes into one, export to excel

In [142]:
df = pd.DataFrame()

for name, value in regionData.items():
    df = pd.concat([df, regionData[name]])

df = df.reset_index(drop=True)
print(df)
df.to_excel('output.xlsx')

     Year        Data       Sheet
0    2018  629.359238  GHG Energy
1    2019   621.79049  GHG Energy
2    2017   615.40825  GHG Energy
3    2007   606.57362  GHG Energy
4    2014  605.859177  GHG Energy
..    ...         ...         ...
619  1993       14.42     CO2-POP
620  1991      14.401     CO2-POP
621  2021      13.219     CO2-POP
622  2022      13.141     CO2-POP
623  2020       13.09     CO2-POP

[624 rows x 3 columns]